### ISSUE TITLE
Review OBO release artefact

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-development-ontology#1]
Review the [OBO release artefact](https://github.com/obophenotype/c-elegans-development-ontology/blob/master/wbls.obo). You should download it, then download the old [wbls.obo ](https://raw.githubusercontent.com/draciti/Life-stage-obo/master/worm_development.obo) then diff them (for example with the command line or whatever other tool you use. 

There will be differences, that is for sure! The question is whether they are acceptable. We will talk about your findings during the next meeting.

**Comment by chris-grove** [comment]
Looks good to me. Closing.

@raymond91125  Please review and reopen if you deem necessary.
