### ISSUE TITLE
Quality control: Fix bugs in ontology

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-development-ontology#2]
A very small [number of bugs](https://github.com/obophenotype/c-elegans-development-ontology/blob/master/reports/wbls-edit-obo-report.tsv) that need fixing.

Please address only after [issue 1](https://github.com/obophenotype/c-elegans-development-ontology/issues/1) is closed.

**Comment by chris-grove** [comment]
OK, all of these are fixed except for two missing definitions which I'm in the process of acquiring/generating.

**Comment by chris-grove** [comment]
OK, I think these are all fixed now (the issues directly pertaining to WBls). Closing.
