### ISSUE TITLE
New term full IRI being dumped as ID in OBO and OWL files, instead of standard "WBls:######" format

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/c-elegans-development-ontology#9]
@matentzn 
I'd like your input on this. For the newest terms I made for the life stage ontology, I accidentally made the IRIs have colons instead of underscores. I don't know if that was an issue (I've since fixed it in edit, and ran a full ODK release), but I'm still seeing the issue where the "id" field for the new terms is being populated with the entire IRI instead of the usual "WBls:#####" format.

Here's an excerpt from wbls.obo from the latest build of the ontology with new terms (IDs 803 to 821):

```
[Term]
id: WBls:0000801
name: newly hatched L1 larval stage Ce
def: "The stage that begins right after hatching and before development proceeds after feeding. A newly hatched L1 larva contains 558 cells." [PMC:4492366, WA:Wormatlas, WB:dr]
is_a: BFO:0000003 ! occurrent
is_a: http://purl.obolibrary.org/obo/WBls:0000817 ! C. elegans life stage occurring during larval stage
relationship: part_of WBls:0000023 ! larva Ce
relationship: preceded_by WBls:0000021 ! fully-elongated embryo Ce
created_by: danielaraciti
creation_date: 2017-11-14T10:14:40Z

[Term]
id: WBls:0000802
name: L1 arrest Ce
def: "The stage in which first stage larvae (L1) that hatch in the absence of food enter a state of developmental arrest." [PMC:3697962, WB:dr]
synonym: "L1 diapause" EXACT []
is_a: BFO:0000003 ! occurrent
is_a: http://purl.obolibrary.org/obo/WBls:0000817 ! C. elegans life stage occurring during larval stage
relationship: part_of WBls:0000801 ! newly hatched L1 larval stage Ce
created_by: danielaraciti
creation_date: 2017-11-14T10:15:40Z

[Term]
id: http://purl.obolibrary.org/obo/WBls:0000803
name: C. elegans life stage occurring during embryogenesis
def: "A C. elegans life stage that occurs during embryogenesis" [WB:WBPerson2987]
is_a: WBls:0000002 ! all stages Ce

[Term]
id: http://purl.obolibrary.org/obo/WBls:0000804
name: C. elegans life stage occurring post embryogenesis
def: "A C. elegans life stage that occurs after embryogenesis" [WB:WBPerson2987]
is_a: WBls:0000002 ! all stages Ce
```

As you can see, the latest terms (made since instantiating ODK) now are populating the "id" with full PURL IRIs, but this is breaking our downstream pipelines (like our ontology browser). Thoughts?

**Comment by matentzn** [comment]
I would run the release again.. the edit file is the source of truth here; I would think that since its fixed there, the release obo file should be fixed as well. Can you run another release and see what it says?

**Comment by chris-grove** [comment]
@matentzn 
FYI, here are the outputs from running the "make prepare_release" yesterday and today:

https://www.dropbox.com/s/vds5by6r32h9wp3/ODK_release_output_June_5_2019.txt?dl=0

https://www.dropbox.com/s/sfh7vjn0vgfpnsl/ODK_release_output_June_6_2019.txt?dl=0

**Comment by chris-grove** [comment]
Fixed. Closing.
